### ISSUE TITLE
[RELEASE 4.1300x] Checklist

### ISSUE THREAD

**Issue by iceman1001** [RfidResearchGroup/proxmark3#1265]
# Checklist

- [x] CHANGELOG.md
- [x] `make style`
- [x] `make clean; make client CC=clang CXX=clang++ LD=clang++` on recent Debian or Ubuntu
- [x] `mymanualchecks.sh`
- [x] `mycppcheck.sh` no alarming warning?
- [x] `mymakeclang.sh` no alarming error/warning ?
- [x] `mystandalone_makes.sh` compile all standalone modes (linux only)
- [x] Github Actions - all green across the board ( Linux, OSX, WIN )
- [x] [Appveyor](https://ci.appveyor.com/project/RfidResearchGroup/proxmark3/history) green (PS)

# OS compilation and tests

```bash
#!/usr/bin/env bash

make clean && make -j PLATFORM=PM3GENERIC && tools/pm3_tests.sh --long
make clean && make -j PLATFORM=PM3RDV4 && tools/pm3_tests.sh --long
make clean && make -j PLATFORM=PM3RDV4 PLATFORM_EXTRAS=BTADDON && tools/pm3_tests.sh --long
sudo make install; pushd /tmp; proxmark3 -c 'data load -f lf_EM4x05.pm3;lf search -1'; popd; sudo make uninstall

( cd client; rm -rf build; mkdir build;cd build;cmake .. && make -j PLATFORM=PM3GENERIC && PM3BIN=./proxmark3 ../../tools/pm3_tests.sh client )
( cd client; rm -rf build; mkdir build;cd build;cmake .. && make -j PLATFORM=PM3RDV4  && PM3BIN=./proxmark3 ../../tools/pm3_tests.sh client )
( cd client; rm -rf build; mkdir build;cd build;cmake .. && make -j PLATFORM=PM3RDV4 PLATFORM_EXTRAS=BTADDON && PM3BIN=./proxmark3 ../../tools/pm3_tests.sh client )
```

- [x] RPI Zero
- [x] WSL
- [x] PSv3.3
- [ ] Kali
- [x] Debian
- [x] Ubuntu20
- [ ] ParrotOS
- [x] Fedora
- [ ] OpenSuse
- [x] OSX
- [ ] Android
- [x] Termux

**Comment by iceman1001** [comment]
The building seems to be working nice.  One thing with GH actions is that it doesn't color its output making it hard to find when there is a warning. 

Potential shopstopers:
Since the conversion to cli-parser,  I suspect minor textual errors in help text.  
@merlokk  will have a look at the Fido refactoring,  he also mention there was some non-working `hf mf autopwn` | `hf mf nested` etc cli parsing.

**Comment by iceman1001** [comment]
@merlokk  found the 14443-4 chaining isn't working.   Which is a show stopper.

**Comment by iceman1001** [comment]
Chaining works, but @merlokk  didn't get around to fix it all,   he be AFK which will set this release on hold until he comes back.

**Comment by iceman1001** [comment]
alright,  so much more was merged into the master...
I guess one more round of testing it all again before a new release is needed. 

But I am excited to see so much new stuff cipurse,  desfire working.

**Comment by iceman1001** [comment]
New release pushed.  closing
