### ISSUE TITLE
Desfire commands checklist

### ISSUE THREAD

**Issue by merlokk** [RfidResearchGroup/proxmark3#1408]
Now works:
keys: `des` / `2tdea` / `3tdea` / `aes`
secure channel: `d40` / `ev1` / `ev2`
command set: `native` / `native iso wrapper`
communication mode : `none` / `plain` / `maced` / `encoded`
in all the variants

Authentication works:
`d40` / `ev1` / `ev2` via  `native` / `native iso wrapper` command set
`iso`  via iso command set 

TODO:
- [x] ev2 channel
- [x] ev2 secure commands like change key, config, etc
- [x] iso commands
- [x] fix iso id byte order
- [x] commands, marked as `[old]` in the command list
- [x] `lsfiles` formatting
- [x] `lsapp` command
- [x] `mad` command
- [x] `detect` command. detect key and key type for application and/or picc
- [x] transactions (https://www.nxp.com/docs/en/data-sheet/MF2DLHX0.pdf)
- [x] move cli from `arg_get_u32_hexstr_def_nlen` to `CLIGetUint32Hex`
- [x] doc file (I think .md in the docs folder) with command logic explanation
- [x] changelog)))

**Comment by iceman1001** [comment]
Amazing refactoring of the desfire support. 

The documentation part is important.
