### ISSUE TITLE
[RELEASE 4.14434] Checklist for release: Crimson

### ISSUE THREAD

**Issue by doegox** [RfidResearchGroup/proxmark3#1495]
# Checklist

- [x] CHANGELOG.md
- [x] `make style`
- [x] `make miscchecks`
- [x] `make clean; make client CC=clang CXX=clang++ LD=clang++` on recent Debian or Ubuntu
- [x] `mymanualchecks.sh`
- [ ] `mycppcheck.sh` no alarming warning?
- [x] `mystandalone_makes.sh` check that the script contains all standalone modes then compile all standalone modes (linux only)
- [x] `experimental_lib` compilation & tests
- [x] `experimental_client_with_swig` compilation & tests
- [x] GitHub Actions - green across the board ( MacOS, Ubuntu, Windows)
- [x] [Appveyor](https://ci.appveyor.com/project/RfidResearchGroup/proxmark3/history) green (PS)

# OS compilation and tests

```bash
#!/usr/bin/env bash

make clean && make -j PLATFORM=PM3GENERIC PLATFORM_EXTRAS= && tools/pm3_tests.sh --long || exit 1
make clean && make -j PLATFORM=PM3RDV4 PLATFORM_EXTRAS= && tools/pm3_tests.sh --long || exit 1
make clean && make -j PLATFORM=PM3RDV4 PLATFORM_EXTRAS=BTADDON && tools/pm3_tests.sh --long || exit 1
make -j PLATFORM=PM3RDV4 PLATFORM_EXTRAS=BTADDON && sudo make install PLATFORM=PM3RDV4 PLATFORM_EXTRAS=BTADDON && ( cd /tmp; proxmark3 -c 'data load -f lf_EM4x05.pm3;lf search -1'|grep 'Valid FDX-B ID found' ) && sudo make uninstall || exit 1

( cd client; rm -rf build; mkdir build;cd build;cmake .. && make -j PLATFORM=PM3GENERIC PLATFORM_EXTRAS= && ../../tools/pm3_tests.sh --clientbin $(pwd)/proxmark3 client ) || exit 1
( cd client; rm -rf build; mkdir build;cd build;cmake .. && make -j PLATFORM=PM3RDV4  PLATFORM_EXTRAS= && ../../tools/pm3_tests.sh --clientbin $(pwd)/proxmark3 client ) || exit 1
( cd client; rm -rf build; mkdir build;cd build;cmake .. && make -j PLATFORM=PM3RDV4 PLATFORM_EXTRAS=BTADDON && ../../tools/pm3_tests.sh --clientbin $(pwd)/proxmark3 client ) || exit 1
```

- [x] RPI Zero
- [x] Jetson Nano
- [x] WSL
- [x] PSv3.10
- [x] Archlinux
- [ ] Kali
- [x] Debian
- [x] Ubuntu21
- [x] ParrotOS 4.11
- [x] Fedora
- [x] OpenSuse Leap
- [x] OpenSuse Tumbleweed
- [x] OSX
- [ ] Android
- [x] Termux

# Creating release
`make release RELEASE_NAME="crimson"`
last line of output,  gives you next command to run
Sample:  `git push && git push origin v4.15000`

### Step Github releases
Go to Github releases,  create release based on the new created tag and publish

### Step Homebrew updates
update homebrew repo, file `proxmark3.rb` with a SHA256 sum of the file `v4.15000.tar.gz`  

### Step package maintains
make a list of new standalone modes,  so when we alert package maintainers they have a sporting chance of adding them

**Comment by iceman1001** [comment]
I believe I got an updated version of the test build script from you @doegox   where it does exit 1.
if this is the prefered way,  I can update the release template to match it.

```
#!/usr/bin/env bash

make clean && make -j PLATFORM=PM3GENERIC && tools/pm3_tests.sh --long || exit 1
make clean && make -j PLATFORM=PM3RDV4 && tools/pm3_tests.sh --long || exit 1
make clean && make -j PLATFORM=PM3RDV4 PLATFORM_EXTRAS=BTADDON && tools/pm3_tests.sh --long || exit 1
make install; pushd /tmp; proxmark3 -c 'data load -f lf_EM4x05.pm3;lf search -1'; popd; make uninstall

( cd client; rm -rf build; mkdir build;cd build;cmake .. && make -j PLATFORM=PM3GENERIC && PM3BIN=./proxmark3 ../../tool
s/pm3_tests.sh client --long ) || exit 1
( cd client; rm -rf build; mkdir build;cd build;cmake .. && make -j PLATFORM=PM3RDV4  && PM3BIN=./proxmark3 ../../tools/
pm3_tests.sh client --long ) || exit 1
( cd client; rm -rf build; mkdir build;cd build;cmake .. && make -j PLATFORM=PM3RDV4 PLATFORM_EXTRAS=BTADDON && PM3BIN=.
/proxmark3 ../../tools/pm3_tests.sh client --long ) || exit 1

```

**Comment by doegox** [comment]
ok I changed it here and in the template

**Comment by iceman1001** [comment]
@msoose  mentioned on discord it compiles just fine some week ago

**Comment by iceman1001** [comment]
@Gator96100  mentioned on discord it compiles just fin on ProxSpace 3.10

**Comment by iceman1001** [comment]
@tcprst  will run it on OSX and on the M2

**Comment by iceman1001** [comment]
@doegox   don't forget to drop a line in CHANGELOG.md for all your commits

**Comment by doegox** [comment]
"gardening for next release"?
Nah it's ok for me

**Comment by tcprst** [comment]
> @tcprst will run it on OSX and on the M2

Tested on Intel and Apple Silicon without issues

**Comment by iceman1001** [comment]
ccache is nice!

**Comment by iceman1001** [comment]
New release is published.
homebrew is updated.   Still need to update the standalone modes possible in that file. 
https://github.com/RfidResearchGroup/homebrew-proxmark3/blob/master/proxmark3.rb#L26-L27

Now, its time to create a list of new standalone files in this release,  to inform all package maintainers.,

**Comment by iceman1001** [comment]
Changelog has been updated to reflect it.
