### ISSUE TITLE
[RELEASE 4.16191] Checklist - release name: Nitride

### ISSUE THREAD

**Issue by iceman1001** [RfidResearchGroup/proxmark3#1868]
# Checklist

- [x] CHANGELOG.md: add title: `## [Nitride][2023-01-29]`
- [x] `make style`
- [x] `make miscchecks`
- [x] `make clean; make client CC=clang CXX=clang++ LD=clang++` on recent Debian or Ubuntu
- [x] `mymanualchecks.sh`
- [x] `mycppcheck.sh` no alarming warning?
- [x] `tools/build_all_firmwares.sh` check that the script contains all standalone modes then compile all standalone modes (linux only)
- [x] `experimental_lib` compilation & tests
- [x] `experimental_client_with_swig` compilation & tests 
- [x] GitHub Actions - green across the board ( MacOS, Ubuntu, Windows)

# OS compilation and tests

```bash
#!/usr/bin/env bash

set -x
make clean && make -j PLATFORM=PM3GENERIC PLATFORM_EXTRAS= && tools/pm3_tests.sh --long || exit 1
make clean && make -j PLATFORM=PM3RDV4 PLATFORM_EXTRAS= || exit 1
make clean && make -j PLATFORM=PM3RDV4 PLATFORM_EXTRAS=BTADDON || exit 1
make -j PLATFORM=PM3RDV4 PLATFORM_EXTRAS=BTADDON && INSTALLSUDO=sudo make install PLATFORM=PM3RDV4 PLATFORM_EXTRAS=BTADDON && ( cd /tmp; proxmark3 -c 'data load -f lf_EM4x05.pm3;lf search -1'|grep 'Valid FDX-B ID
found' ) && INSTALLSUDO=sudo make uninstall || exit 1
( cd client; rm -rf build; mkdir build;cd build;cmake .. && make -j PLATFORM=PM3GENERIC PLATFORM_EXTRAS= && cp -a ../*scripts ../*libs . && ../../tools/pm3_tests.sh --clientbin $(pwd)/proxmark3 client ) || exit 1
( cd client; rm -rf build; mkdir build;cd build;cmake .. && make -j PLATFORM=PM3RDV4 PLATFORM_EXTRAS= ) || exit 1
( cd client; rm -rf build; mkdir build;cd build;cmake .. && make -j PLATFORM=PM3RDV4 PLATFORM_EXTRAS=BTADDON ) || exit 1

# Hitag2crack, optionally with --long and --opencl ...
make hitag2crack/clean && make hitag2crack && tools/pm3_tests.sh hitag2crack || exit 1
echo PASS
```

- [x] RPI Zero
- [x] Jetson Nano
- [x] WSL
- [ ] PSv3.10
- [x] Archlinux
- [x] Kali
- [x] Debian Stable
- [x] Debian Testing
- [x] Ubuntu 22
- [x] ParrotOS
- [x] Fedora 37
- [x] OpenSuse Leap
- [x] OpenSuse Tumbleweed
- [x] OSX (MacPorts)
- [ ] OSX (Homebrew)
- [ ] Android
- [x] Termux

# creating release

- [x] `make release RELEASE_NAME="Nitride"`
  - last line of output,  gives you next command to run.
  - Sample:  `git push && git push origin v4.16191`
- [x] CHANGELOG.md: edit title to add version info: `## [Nitride.4.16191][2023-01-29]`

## Step Github releases

- [x] Go to Github releases,  create release based on the new created tag and publish

## Step Homebrew updates

- [x] update homebrew repo, file `proxmark3.rb`
  - with a SHA256 sum of the file `v4.16191.tar.gz`
  - with updated list of standalone modes

## Step package maintains

- [x] make a list of new standalone modes, so when we alert package maintainers they have a sporting chance of adding them

**Comment by doegox** [comment]
I fixed a few things since my last tests, but I won't re-run all tests every time there are new changes... Please fix a RC and then we only fix things then make a release, but no new stuff.

**Comment by iceman1001** [comment]
That is a fair request, 

As I know of now,  Its one more thing,  the preference.json saving ,  that is needed for a release.

**Comment by iceman1001** [comment]
Alright,  done,  

all compiles on : 

RPI Zero
Jetson Nano
WSL
Archlinux
Kali
Ubuntu 22
ParrotOS
Fedora 37
OpenSuse Tumbleweed
Termux


the build_all firmware fails,   since the generic is too big for 256kb, 

I think its more or less ready for a release.   If you don't find anything,  I be releasing tomorrow

**Comment by doegox** [comment]
> the build_all firmware fails, since the generic is too big for 256kb

Ok then we need to skip sth else for 256kb devices, so we can at least test the compilation of all the other firmwares. I chose arbitrarily to skip NFCBARCODE support: https://github.com/RfidResearchGroup/proxmark3/commit/2633a54e11670a0144bcf11ce308b3eba644773c

**Comment by iceman1001** [comment]
Ok, 

There are some new entries for coverity I pushed fixes to,   and then its done.

**Comment by iceman1001** [comment]
:(  skip nfcbarcode isn't enough.  
I added  `SKIP_ZX8211=1`  to make it work.

**Comment by iceman1001** [comment]
New standalone modes in this release:
``` 
LF_NEDAP_SIM
LF_PROX2BRUTE
```
