### ISSUE TITLE
[RELEASE 4.16717] Checklist - release name: Seven

### ISSUE THREAD

**Issue by iceman1001** [RfidResearchGroup/proxmark3#1939]
# Checklist

- [x] CHANGELOG.md: add title: `## [seven][YYYY-MM-DD]`
- [x] `make style`
- [x] `make miscchecks`
- [x] `make clean; make client CC=clang CXX=clang++ LD=clang++` on recent Debian or Ubuntu
- [x] `mymanualchecks.sh`
- [ ] `mycppcheck.sh` no alarming warning?
- [x] `tools/build_all_firmwares.sh` check that the script contains all standalone modes then compile all standalone modes (linux only)
- [x] `experimental_lib` compilation & tests
- [x] `experimental_client_with_swig` compilation & tests
- [x] GitHub Actions - green across the board ( MacOS, Ubuntu, Windows )

# OS compilation and tests

Run `tools/release_tests.sh` on:

- [x] RPI Zero
- [x] Jetson Nano
- [x] WSL
- [x] PSv3.10
- [x] Archlinux
- [x] Kali
- [x] Debian Stable
- [ ] Debian Testing
- [x] Ubuntu 22
- [x] ParrotOS
- [x] Fedora 37
- [ ] OpenSuse Leap
- [x] OpenSuse Tumbleweed
- [ ] OSX (MacPorts)
- [ ] OSX (Homebrew)
- [x] Android
- [x] Termux

# creating release

- [x] `make release RELEASE_NAME="seven"`
  - last line of output,  gives you next command to run.
  - Sample:  `git push && git push origin v4.16717`
- [x] CHANGELOG.md: edit title to add version info: `## [seven.4.16717][YYYY-MM-DD]`

## Step Github releases

- [x] Go to Github releases,  create release based on the new created tag and publish

## Step Homebrew updates

- [x] update homebrew repo, file `proxmark3.rb`
  - with a SHA256 sum of the file `v4.16717.tar.gz`
  - with updated list of standalone modes

## Step package maintains

- [ ] make a list of new standalone modes, so when we alert package maintainers they have a sporting chance of adding them

**Comment by SnakePin** [comment]
Tried the following command on Ubuntu 22.04 with Clang 17.0.0(9548af05):
`make clean; make client CC=clang CXX=clang++ LD=clang++`
and I just got a single warning, other than that it compiles fine.
```
src/flash.c:349:32: warning: cast from 'uint8_t *' (aka 'unsigned char *') to 'uint32_t *' (aka 'unsigned int *') increases required alignment from 1 to 4 [-Wcast-align]
            uint32_t offset = *(uint32_t *)(ctx->elf + le32(shdrs[i].sh_offset) + le32(shdrs[i].sh_size) - 4);
```

**Comment by iceman1001** [comment]
Thank you for mention it.  We are aware of it existence when compiling with CLANG. 

The assigned array isnt checked for being evenly dividable with four so the compiler rightfully complains a bit

**Comment by iceman1001** [comment]
@wh201906    
Nice android build script you made.

**Comment by iceman1001** [comment]
Release done!
Thank you everyone for the efforts to bring this release out.
