### ISSUE TITLE
[RELEASE 4.17139] Checklist - release name: Raccoon

### ISSUE THREAD

**Issue by iceman1001** [RfidResearchGroup/proxmark3#2104]
# Checklist

- [x] CHANGELOG.md: add title: `## [Raccoon]2023-09-09]`
- [x] `make style`
- [x] `make miscchecks`
- [x] `make clean; make client CC=clang CXX=clang++ LD=clang++` on recent Debian or Ubuntu
- [x] `mymanualchecks.sh`
- [x] `mycppcheck.sh` no alarming warning?
- [x] `tools/build_all_firmwares.sh` check that the script contains all standalone modes then compile all standalone modes (linux only)
- [x] `experimental_lib` compilation & tests
- [ ] `experimental_client_with_swig` compilation & tests
- [x] GitHub Actions - green across the board ( MacOS, Ubuntu, Windows)

# OS compilation and tests

Run `tools/release_tests.sh` on:

- [x] RPI Zero
- [x] Jetson Nano
- [x] WSL
- [ ] PSv3.10
- [x] Archlinux
- [x] Kali
- [x] Debian Stable
- [x] Debian Testing
- [x] Ubuntu 22
- [x] ParrotOS
- [x] Fedora 37
- [x] OpenSuse Leap
- [x] OpenSuse Tumbleweed
- [x] OSX (MacPorts)
- [x] OSX (Homebrew)
- [x] Android
- [x] Termux

# creating release

- [x] `make release RELEASE_NAME="Raccoon"`
  - last line of output,  gives you next command to run.
  - Sample:  `git push && git push origin v4.17139`
- [x] CHANGELOG.md: edit title to add version info: `## [Raccoon.4.17139]2023-09-09]`

## Step Github releases

- [x] Go to Github releases,  create release based on the new created tag and publish

## Step Homebrew updates

- [x] update homebrew repo, file `proxmark3.rb`
  - with a SHA256 sum of the file `v4.17139.tar.gz`
  - with updated list of standalone modes

## Step package maintains

- [x] make a list of new standalone modes, so when we alert package maintainers they have a sporting chance of adding them

**Comment by doegox** [comment]
FTR SWIG & Python seems broken since the attempt to migrate the API when I run it with Python 3.11
I suspect the problem appeared with a new version of Python, I'm pretty sure we tested it at that time and it was fine (https://github.com/RfidResearchGroup/proxmark3/issues/1870)

**Comment by iceman1001** [comment]
Could be,  I rarely run the SWIG compilation,    running python 3.10.12 on WSL1 / Ubuntu ...
Haven't gone over to 3.11 yet.   GCC11 though.

**Comment by doegox** [comment]
ok it works fine with Python 3.9 and fails with 3.11 (no 3.10 around here), but the code of `cmdscript.c` is very different for Python >= 10. No idea how to fix that.

**Comment by iceman1001** [comment]
Nice!  Maybe for another release.

**Comment by doegox** [comment]
I'm finishing Tumbleweed tests (and I need to push fix on its docker scripts) then I'm done.

**Comment by doegox** [comment]
:green_apple: :green_book: :green_heart: :green_salad:

**Comment by iceman1001** [comment]
Only one new standalone mode:  

```
HF_CARDHOPPER |	Relay 14a protocols over long distances (w/ IP backbone) | Sam Haskins | RDV4
```
