### ISSUE TITLE
[RELEASE 4.x] Checklist

### ISSUE THREAD

**Issue by k0x3v** [RfidResearchGroup/proxmark3#2148]
# Checklist

- [x] CHANGELOG.md: add title: `## [releasename][YYYY-MM-DD]`
- [x] `make style`
- [x] `make miscchecks`
- [x] `make clean; make client CC=clang CXX=clang++ LD=clang++` on recent Debian or Ubuntu
- [x] `mymanualchecks.sh`
- [x] `mycppcheck.sh` no alarming warning?
- [x] `tools/build_all_firmwares.sh` check that the script contains all standalone modes then compile all standalone modes (linux only)
- [x] `experimental_lib` compilation & tests
- [x] `experimental_client_with_swig` compilation & tests
- [x] GitHub Actions - green across the board ( MacOS, Ubuntu, Windows)

# OS compilation and tests

Run `tools/release_tests.sh` on:

- [x] RPI Zero
- [x] Jetson Nano
- [x] WSL
- [x] PSv3.10
- [x] Archlinux
- [x] Kali
- [x] Debian Stable
- [x] Debian Testing
- [x] Ubuntu 22
- [x] ParrotOS
- [x] Fedora 37
- [x] OpenSuse Leap
- [x] OpenSuse Tumbleweed
- [x] OSX (MacPorts)
- [x] OSX (Homebrew)
- [x] Android
- [x] Termux

# creating release

- [x] `make release RELEASE_NAME="ice awesome"`
  - last line of output,  gives you next command to run.
  - Sample:  `git push && git push origin v4.12345`
- [x] CHANGELOG.md: edit title to add version info: `## [releasename.4.12345][YYYY-MM-DD]`

## Step Github releases

- [x] Go to Github releases,  create release based on the new created tag and publish

## Step Homebrew updates

- [x] update homebrew repo, file `proxmark3.rb`
  - with a SHA256 sum of the file `v4.12345.tar.gz`
  - with updated list of standalone modes

## Step package maintains

- [x] make a list of new standalone modes, so when we alert package maintainers they have a sporting chance of adding them

**Comment by doegox** [comment]
this type of issue is reserved to maintainers, thank you
