### ISSUE TITLE
[RELEASE 4.17496] Checklist - release name:  Faraday

### ISSUE THREAD

**Issue by iceman1001** [RfidResearchGroup/proxmark3#2158]
# Checklist

- [x] CHANGELOG.md: add title: `## [Faraday][YYYY-MM-DD]`
- [x] `make style`
- [x] `make miscchecks`
- [x] `make clean; make client CC=clang CXX=clang++ LD=clang++` on recent Debian or Ubuntu
- [x] `mymanualchecks.sh`
- [x] `mycppcheck.sh` no alarming warning?
- [x] `tools/build_all_firmwares.sh` check that the script contains all standalone modes then compile all standalone modes (linux only)
- [x] `experimental_lib` compilation & tests
- [x] `experimental_client_with_swig` compilation & tests
- [x] GitHub Actions - green across the board ( MacOS, Ubuntu, Windows)

# OS compilation and tests

Run `tools/release_tests.sh` on:

- [x] RPI Zero
- [x] Jetson Nano
- [x] WSL
- [ ] PSv3.10
- [x] Archlinux
- [x] Kali
- [x] Debian Stable
- [x] Debian Testing
- [x] Ubuntu 22
- [x] ParrotOS
- [x] Fedora 37
- [x] OpenSuse Leap
- [x] OpenSuse Tumbleweed
- [ ] OSX (MacPorts)
- [ ] OSX (Homebrew)
- [ ] Android
- [ ] Termux

# creating release

- [x] `make release RELEASE_NAME="Faraday"`
  - last line of output,  gives you next command to run.
  - Sample:  `git push && git push origin v4.17496`
- [x] CHANGELOG.md: edit title to add version info: `## [Faraday.4.17496][YYYY-MM-DD]`

## Step Github releases

- [x] Go to Github releases,  create release based on the new created tag and publish

## Step Homebrew updates

- [x] update homebrew repo, file `proxmark3.rb`
  - with a SHA256 sum of the file `v4.17496.tar.gz`
  - with updated list of standalone modes

## Step package maintains

- [x] make a list of new standalone modes, so when we alert package maintainers they have a sporting chance of adding them

**Comment by doegox** [comment]
my tests ok, except experimental_client_with_swig still broken as for previous release https://github.com/RfidResearchGroup/proxmark3/issues/2104

**Comment by doegox** [comment]
now experimental_client_with_swig fixed

**Comment by doegox** [comment]
no new standalone modes

**Comment by doegox** [comment]
https://github.com/RfidResearchGroup/proxmark3/releases/tag/v4.17511
