### ISSUE TITLE
[RELEASE 4.17767] Checklist - release name Steamboat Willie

### ISSUE THREAD

**Issue by iceman1001** [RfidResearchGroup/proxmark3#2228]
# Checklist

- [x] `make style`
- [x] `make miscchecks`
- [x] `make clean; make client CC=clang CXX=clang++ LD=clang++` on recent Debian or Ubuntu
- [ ] `mymanualchecks.sh`
- [ ] `mycppcheck.sh` no alarming warning?
- [x] `tools/build_all_firmwares.sh` check that the script contains all standalone modes then compile all standalone modes (linux only)
- [x] `experimental_lib` compilation & tests
- [x] `experimental_client_with_swig` compilation & tests
- [x] GitHub Actions - green across the board ( MacOS, Ubuntu, Windows)

# OS compilation and tests

Run `tools/release_tests.sh` on:

- [x] RPI Zero
- [x] Jetson Nano
- [x] WSL
- [ ] PSv3.10
- [x] Archlinux
- [x] Kali
- [x] Debian Stable
- [x] Debian Testing
- [x] Ubuntu 22
- [x] ParrotOS
- [x] Fedora 37
- [x] OpenSuse Leap
- [ ] OpenSuse Tumbleweed
- [ ] OSX (MacPorts)
- [ ] OSX (Homebrew)
- [x] Android
- [x] Termux
- [x] iOS

# creating release

- [x] CHANGELOG.md: add title: `## [Steamboat Willie][YYYY-MM-DD]`
- [x] `make release RELEASE_NAME="Steamboat Willie"`
  - last line of output gives you next command to run.
  - Sample:  `git push && git push origin v4.17768`
- [x] CHANGELOG.md: edit title to add version info: `## [Steamboat Willie.4.17768][YYYY-MM-DD]`

## Step Github releases

- [x] Go to Github releases,  create release based on the new created tag and publish
  - Choose a tag: v4.17768
  - Target: master
  - Set as the latest release
  - Title: `proxmark3-v4.17768`
  - Description:
```
Release v4.17768
Nickname "Steamboat Willie"
```

## Step Homebrew updates

- [x] update homebrew repo, file `proxmark3.rb`
  - with a SHA256 sum of the file `v4.17768.tar.gz`
  - with updated list of standalone modes

## Step package maintains

- [x] make a list of new standalone modes, so when we alert package maintainers they have a sporting chance of adding them

**Comment by iceman1001** [comment]
New standalone mode in this release:  `hf_unisniff`  

And from the previous release we also had `hf_cardhopper`

**Comment by iceman1001** [comment]
@doegox  are you able to run the docker environment tests?

**Comment by doegox** [comment]
visibly you managed it :)
