### ISSUE TITLE
[RELEASE 4.18218] Checklist - release name "DEFCON is Cancelled"

### ISSUE THREAD

**Issue by iceman1001** [RfidResearchGroup/proxmark3#2294]
# Checklist

- [x] `make style`
- [x] `make miscchecks`
- [x] `make clean; make client CC=clang CXX=clang++ LD=clang++` on recent Debian or Ubuntu
- [x] `mymanualchecks.sh`
- [ ] `mycppcheck.sh` no alarming warning?
- [x] `tools/build_all_firmwares.sh` check that the script contains all standalone modes then compile all standalone modes (linux only)
- [x] `experimental_lib` compilation & tests
- [x] `experimental_client_with_swig` compilation & tests
- [x] GitHub Actions - green across the board ( MacOS, Ubuntu, Windows)

# OS compilation and tests

Run `tools/release_tests.sh` on:

- [x] RPI Zero
- [x] Jetson Nano
- [x] WSL
- [x] PSv3.10
- [ ] Archlinux
- [x] Kali
- [x] Debian Stable
- [x] Debian Testing
- [x] Ubuntu 22
- [ ] ParrotOS
- [x] Fedora 37
- [ ] OpenSuse Leap
- [ ] OpenSuse Tumbleweed
- [x] OSX (MacPorts)
- [x] OSX (Homebrew)
- [ ] Android
- [x] Termux

# creating release

- [x] CHANGELOG.md: add title: `## [DEFCON is Cancelled][YYYY-MM-DD]`
- [x] `make release RELEASE_NAME="DEFCON is Cancelled"`
  - last line of output gives you next command to run.
  - Sample:  `git push && git push origin v4.18218`
- [x] CHANGELOG.md: edit title to add version info: `## [DEFCON is Cancelled.4.18218][YYYY-MM-DD]`

## Step Github releases

- [x] Go to Github releases,  create release based on the new created tag and publish
  - Choose a tag: v4.18218
  - Target: master
  - Set as the latest release
  - Title: `proxmark3-v4.18218`
  - Description:
```
Release v4.18218
Nickname "DEFCON is Cancelled"
```

## Step Homebrew updates

- [x] update homebrew repo, file `proxmark3.rb`
  - with a SHA256 sum of the file `v4.18218.tar.gz`
  - with updated list of standalone modes

## Step package maintains

- [x] make a list of new standalone modes, so when we alert package maintainers they have a sporting chance of adding them

**Comment by iceman1001** [comment]
Clang warns with memory alignment casting in `cmdlfem4x05.c`


![image](https://github.com/RfidResearchGroup/proxmark3/assets/8577004/2096ceba-cadb-4f56-82d0-5dc5f9376d21)

**Comment by iceman1001** [comment]
For experimental builds,  the test script for python,  indicates that `script run <file.py>`  doesnt look in current execution directory.  While running the lua test script works just fine.    Seems to be a python file search path bug somewhere.

moving the scripts allows for correct execution .    


![image](https://github.com/RfidResearchGroup/proxmark3/assets/8577004/d812e5fa-9a60-44b2-9e5d-888d644e0ff6)
