### ISSUE TITLE
[RELEASE 4.18340] Checklist - release name "Zenith" 

### ISSUE THREAD

**Issue by iceman1001** [RfidResearchGroup/proxmark3#2334]
# Checklist

- [x] `make style`
- [x] `make miscchecks`
- [x] `make clean; make client CC=clang CXX=clang++ LD=clang++` on recent Debian or Ubuntu
- [x] `mymanualchecks.sh`
- [ ] `mycppcheck.sh` no alarming warning?
- [x] `tools/build_all_firmwares.sh` check that the script contains all standalone modes then compile all standalone modes (linux only)
- [x] `experimental_lib` compilation & tests
- [x] `experimental_client_with_swig` compilation & tests
- [x] GitHub Actions - green across the board ( MacOS, Ubuntu, Windows)

# OS compilation and tests

Run `tools/release_tests.sh` on:

- [x] RPI Zero
- [ ] Jetson Nano
- [x] WSL
- [ ] PSv3.xx
- [ ] Archlinux
- [x] Kali
- [x] Debian Stable
- [ ] Debian Testing
- [x] Ubuntu 22
- [ ] ParrotOS
- [x] Fedora 37
- [ ] OpenSuse Leap
- [ ] OpenSuse Tumbleweed
- [x] OSX (MacPorts)
- [ ] OSX (Homebrew)
- [ ] Android
- [x] Termux

# creating release

- [x] CHANGELOG.md: add title: `## [Zenith][YYYY-MM-DD]`
- [x] `make release RELEASE_NAME="Zenith"`
  - last line of output gives you next command to run.
  - Sample:  `git push && git push origin v4.18340`
- [x] CHANGELOG.md: edit title to add version info: `## [Zenith.4.18340][YYYY-MM-DD]`

## Step Github releases

- [x] Go to Github releases,  create release based on the new created tag and publish
  - Choose a tag: v4.18340
  - Target: master
  - Set as the latest release
  - Title: `proxmark3-v4.18340`
  - Description:
```
Release v4.18340
Nickname "Zenith"
```

## Step Homebrew updates

- [x] update homebrew repo, file `proxmark3.rb`
  - with a SHA256 sum of the file `v4.18340.tar.gz`
  - with updated list of standalone modes

## Step package maintains

- [ ] make a list of new standalone modes, so when we alert package maintainers they have a sporting chance of adding them
