### ISSUE TITLE
add "make install"

### ISSUE THREAD

**Issue by ZeroChaos-** [RfidResearchGroup/proxmark3#325]
I don't know if this is right, but this is how we do install in pentoo:
```
src_install(){
    #dobin client/{flasher,proxmark3,fpga_compress}
    dobin client/{flasher,proxmark3}
    #install scripts too
    insinto /usr/share/proxmark3/lualibs
    doins client/lualibs/*
    insinto /usr/share/proxmark3/scripts
    doins client/scripts/*
    if use firmware; then
        insinto /usr/share/proxmark3
        doins armsrc/obj/*.elf
        doins bootrom/obj/bootrom.elf
        doins recovery/*.bin
        doins tools/mfkey/mfkey{32,64}
    fi  
    udev_dorules driver/77-pm3-usb-device-blacklist.rules
}
```

basically, flasher and proxmark3 and dropped in /usr/bin, lualibs and scripts are dropped in /usr/share/proxmark3/, and if built, firmware is dropped in /usr/share/proxmark3.  udev rules are put into /lib/udev/rules.d/.

Things are different for me, the defaults should be /usr/local/bin, /usr/local/share/proxmark3, and /etc/udev/rules.d/ for users installing manually.  I can help write the make file if someone can comment about how "correctly" I've done things :-)

Also, it would be awesome to rename the extremely generic "flasher"

**Comment by doegox** [comment]
For comparison, see also current brew formula https://github.com/RfidResearchGroup/homebrew-proxmark3/blob/master/proxmark3.rb#L38-L79

Let's try to recap what it should be:
```
# Linux/ProxSpace/WSL
PREFIX=/usr/local
# OSX with brew
PREFIX=/usr/local/Cellar/proxmark3/HEAD-<Commit-ID>

$PREFIX/bin/proxmark3
$PREFIX/bin/proxmark3.sh (<= a bit confusing... rename it pm3 as for short/quick launcher ?)
$PREFIX/bin/proxmark3-flasher
# fpga_compress doesn't need to be installed, it's useless outside compilation
$PREFIX/bin/proxmark3-flash-all.sh
$PREFIX/bin/proxmark3-flash-bootrom.sh
$PREFIX/bin/proxmark3-flash-fullimage.sh
$PREFIX/bin/mfkey32
$PREFIX/bin/mfkey32v2
$PREFIX/bin/mfkey64
$PREFIX/bin/nonce2key

$PREFIX/share/proxmark3/lualibs
$PREFIX/share/proxmark3/luascripts (currently scripts)

$PREFIX/share/proxmark3/smartcard/capk.txt
$PREFIX/share/proxmark3/smartcard/aidlist.json
$PREFIX/share/proxmark3/smartcard/oids.json
$PREFIX/share/proxmark3/smartcard/fido2_defparams.json (currently fido2.json)
$PREFIX/share/proxmark3/smartcard/emv_defparams.json

$PREFIX/share/proxmark3/hardnested/bf_bench_data.bin
$PREFIX/share/proxmark3/hardnested/tables/*

# these are nice for newcomers to learn I think
$PREFIX/share/proxmark3/traces

# These files will need better names, for now it's
$PREFIX/share/proxmark3/dictionaries/{bmp,icbmp,mrzd}_sort_keys.dic
$PREFIX/share/proxmark3/dictionaries/default_keys.dic
$PREFIX/share/proxmark3/dictionaries/default_{iclass,ultralight}_keys.dic
$PREFIX/share/proxmark3/dictionaries/default_pwd.dic

$PREFIX/share/proxmark3/firmware/bootrom.elf
$PREFIX/share/proxmark3/firmware/fullimage.elf
$PREFIX/share/proxmark3/firmware/SIM011
$PREFIX/share/proxmark3/firmware/SIM011.sha512.txt

# Linux only:
/etc/udev/rules.d/77-pm3-usb-device-blacklist.rules
```

This requires of course adaptations of the code to find its data.
It also goes with modifications for the user files:
```
~/.proxmark3/history (current .history)
~/.proxmark3/log.txt (current proxmark3.log)
~/.proxmark3/dictionaries/ (user dics)
~/.proxmark3/luascripts/ (user lua scripts)
~/.proxmark3/cmdscripts/ (user cli scripts)
~/.proxmark3/smartcard/fido2.json (user fido prefs)
```

I believe user traces and dumps should go to their current working directory, not in `~/.proxmark3`

Maybe we should also think of some history/log rotation, else people will forget these files and they'll grow and grow...

Please comment and tell me if sth is wrong or missing.

There are a bunch of useful tools tp handle EML files, what should we do?
```
eml2lower.sh
eml2UPPER.sh
pm3_mfdread.py
pm3_mfd2eml.py
pm3_eml2mfd.py
pm3_eml_mfd_test.py
```

**Comment by iceman1001** [comment]
as discussed elsewhere,  lets us start changing some stuff inside the repo,  in order to make things even clearer.   like renaming client/scripts -> client/luascripts etc..  I am guess by the time I write this @doegox  has already changed it.

**Comment by doegox** [comment]
Yeah I started.
Don't worry it will be more flexible than my first move on luascripts, with overridable PREFIX defaulting to /use/local and to ??? with brew

**Comment by doegox** [comment]
what about these ones @iceman1001 ? 
```
client/loclass/ikeys.c
663:    if (fileExists("iclass_key.bin")) {
665:    } else if (fileExists("loclass/iclass_key.bin")) {
667:    } else if (fileExists("client/loclass/iclass_key.bin")) {

client/loclass/elite_crack.c
618:        if (fileExists("iclass_dump.bin")) {
620:        } else if (fileExists("loclass/iclass_dump.bin")) {
622:        } else if (fileExists("client/loclass/iclass_dump.bin")) {
```
are they supposed to be in the repo and installed ? I see a client/loclass/iclass_dump.bin in the repo.

**Comment by iceman1001** [comment]
welll...  
yes, iclass_dump.bin is a testfile for **hf iclass loclass**
and there are more files,  "iclass_decryption.bin" ,  which is user provided.  
iclass_key.bin == masterkey leaked.
iclass_Decryptionkey.bin == hid transport 3des key

Those files should be searched for in all our places..

**Comment by edward-p** [comment]
> PREFIX=/usr/local

I think `PREFIX:=/usr/local` is better. So it can be override like `make PREFIX=/usr`.

**Comment by iceman1001** [comment]
@doegox   I think all those fido.json, smartcard.json, aid.json,  iclassfiles,  should be direct under  /.promark3/  no need to complicate it with subfolders with one lone file inside.

**Comment by edward-p** [comment]
> /etc/udev/rules.d/77-pm3-usb-device-blacklist.rules

For user who build the project themselves `/etc/udev/rules.d/77-pm3-usb-device-blacklist.rules` is a good choice. But for package maintainers, `/usr/lib/udev/rules.d77-pm3-usb-device-blacklist.rules`  will be better. So I think something like `UDEV_PREFIX:=/etc/udev/rules.d` is better.

**Comment by doegox** [comment]
> > PREFIX=/usr/local
> 
> I think `PREFIX:=/usr/local` is better. So it can be override like `make PREFIX=/usr`.

Because a make install compatible with brew requires to separate bin & share, we can't work with a unique PREFIX, so we're using overridable PM3_BIN_PATH and PM3_SHARE_PATH, defaulting to /usr/local/bin/ and /usr/local/share/proxmark3/

**Comment by edward-p** [comment]
> Because a make install compatible with brew requires to separate bin & share, we can't work with a unique PREFIX, so we're using overridable PM3_BIN_PATH and PM3_SHARE_PATH, defaulting to /usr/local/bin/ and /usr/local/share/proxmark3/

That's acceptable.

**Comment by doegox** [comment]
> I think something like `UDEV_PREFIX:=/etc/udev/rules.d` is better.

ok

**Comment by doegox** [comment]
> all those fido.json, smartcard.json, aid.json, iclassfiles, should be direct under /.promark3/

ok, so installed under /usr/local/share/proxmark3/

**Comment by iceman1001** [comment]
yeah.  let have them all in one place.

**Comment by iceman1001** [comment]
And lets have ParrotOS maintainer tagged here.  (debian packaging and tag me @palinurosec)

We now have,   Pentoo/Gentoo/Archlinux/ParrotOS   ..

not to mention Homebrew but thats not the same.

**Comment by iceman1001** [comment]
Hm,  Kali and Nethunter left.

**Comment by doegox** [comment]
> > PREFIX=/usr/local
> 
> I think `PREFIX:=/usr/local` is better. So it can be override like `make PREFIX=/usr`.

For my own understanding, could you elaborate on `:=` vs `=` ?
Currently we have `CC = gcc` and we can override it with `make CC=clang`, no need for `:=` I think.

**Comment by ZeroChaos-** [comment]
I don't really understand := vs ?=, but documentation is here:
https://www.gnu.org/software/make/manual/html_node/Setting.html#Setting

It is generally nice to use ?= in place of = for CC et al, but as you see it's not required

**Comment by doegox** [comment]
well `?=` is a different story... we use it for CFLAGS but we can't for CC because CC is predefined by make as `cc`:

```
$(info $(CC))
CC?=gcc
$(info $(CC))
CC=gcc
$(info $(CC))
```
=>
```
make
cc
cc
gcc
```
```
CC=foo make
foo
foo
gcc
```
```
make CC=foo
foo
foo
foo
```

**Comment by edward-p** [comment]
> > > PREFIX=/usr/local
> > 
> > 
> > I think `PREFIX:=/usr/local` is better. So it can be override like `make PREFIX=/usr`.
> 
> For my own understanding, could you elaborate on `:=` vs `=` ?
> Currently we have `CC = gcc` and we can override it with `make CC=clang`, no need for `:=` I think.

Ah, I got a bad memory. Actually I mean `?=`. So it can be override by environment variables.

**Comment by ZeroChaos-** [comment]
This is an updated copy of how I install (live in my git repo) to help build make install (or tell me I'm doing it wrong)
https://github.com/pentoo/pentoo-overlay/blob/master/net-wireless/proxmark3/proxmark3-9999.ebuild

**Comment by doegox** [comment]
> This is an updated copy of how I install (live in my git repo) to help build make install (or tell me I'm doing it wrong)

* astyle is a `suggest` dependency, not a strong dependency (only for committers actually)
* hf-mattyrun -> HF_MATTYRUN
* hf_colin -> HF_COLIN
* hf_bog -> HF_BOG
* maybe no need for jtag/recovery stuff to be deployed

**Comment by ZeroChaos-** [comment]
what are these files for?
```
$PM3_SHARE_PATH/firmware/SIM011
$PM3_SHARE_PATH/firmware/SIM011.sha512.txt
```
thanks for the updates :-)

**Comment by merlokk** [comment]
For update iso7816 module. I'm not sure if it needs to install

**Comment by iceman1001** [comment]
It is the firmware for SIM Module.

SIM011 and the sha512,  is very much needed.   
From factory,  it doesn't contain latest firmware for the simmodule,   SIM011.bin is the latest fw and the sha512 is used for verfication of the firmware file during upgrade.

**Comment by iceman1001** [comment]
@ZeroChaos-   your nice live update iin your repo,  does it use those patches you have aswell?
Do you still need it:  https://github.com/pentoo/pentoo-overlay/blob/master/net-wireless/proxmark3/files/cflags.patch

**Comment by ZeroChaos-** [comment]
@iceman1001 no, that file wasn't used anymore, I cleared it :-)

What about SIM0110?

**Comment by iceman1001** [comment]
> It is the firmware for SIM Module.
> 
> SIM011 and the sha512, is very much needed.
> From factory, it doesn't contain latest firmware for the simmodule, SIM011.bin is the latest fw and the sha512 is used for verfication of the firmware file during upgrade.

**Comment by ZeroChaos-** [comment]
probably want to rename tools/simmodule/readme.txt to something less likely to collide so it can be installed in /usr/share/proxmark3/firmware with the files so folks know what they are.

and sorry, had a typo in that last one, what about SIM010.BIN?

**Comment by iceman1001** [comment]
SIM010.bin is the previous fw.
SIM011 is the latest.

**Comment by doegox** [comment]
ignore the readme.txt for now, its content should be migrated in the docs/

**Comment by edward-p** [comment]
Do `PM3RDV4` and `PM3OTHER` share any targets?

- [ ] bootrom
- [ ] os
- [ ] flash-bootrom
- [ ] flash-os
- [ ] flash-all
- [ ] recovery
- [ ] client
- [ ] mfkey
- [ ] nonce2key
- [ ] fpga_compress

I want know if I can package one package for both  `PM3RDV4` and `PM3OTHER`.

**Comment by doegox** [comment]
Common:

- [x] bootrom
- [ ] os
- [x] flash-bootrom > not for packaging
- [x] flash-os > not for packaging
- [x] flash-all> not for packaging
- [ ] recovery
- [x] client
- [x] mfkey
- [x] nonce2key
- [x] fpga_compress > not for packaging

**Comment by doegox** [comment]
So basically you only need to bring both fullimage.elf and possibly both proxmark3_recovery.bin if you really want to ship systematically JTAG images...

**Comment by doegox** [comment]
But IMHO if someone needs to operate JTAG because he bricked his device, he should be skilled enough to work with the git repo

**Comment by doegox** [comment]
But IMHO if someone needs to operate JTAG because he bricked his device, he should be skilled enough to work with the git repo

**Comment by iceman1001** [comment]
We don't use "os"  any longer.  We only use the combined new  "fullimage" since a couple of years back.
os + fpga images = fullimage.

I would like to that you all have  proxmark3_recovery.bin 
Its an easy file to keep,  if you jtag you maybe still don't want to git clone if you did a make install....

**Comment by doegox** [comment]
@iceman1001 "os" was referring to the make Target, `make os` to get fullimage

**Comment by iceman1001** [comment]
its still called `make os` ???  hmm..   that should be renamed to `make fullimage` ?

**Comment by doegox** [comment]
yep, this is more coherent, done. `make fullimage` (and added `make fullimage/clean` support)

**Comment by doegox** [comment]
Hmm I realize the current brew was just wrong on its share path and should be `$PM3_BREW_PREFIX/share/proxmark3`, so we can just live with the usual PREFIX in the makefile and it will work fine for brew too, I'll change that soon.

**Comment by iceman1001** [comment]
I change homebrew to share/proxmark3 ,  hardcoded :)

**Comment by edward-p** [comment]
For those shell scripts (which need `PM3_SHARE_PATH`):

- flash-all.sh
- flash-bootrom.sh
- flash-fullimage.sh

Should hardcode with `@PM3_SHARE_PATH@`, then be replaced when installing?

**Comment by edward-p** [comment]
This is currently how I package the Arch Linux package: [PKGBUILD](https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/proxmark3-iceman-git/PKGBUILD)

**Comment by doegox** [comment]
hmm true, the scripts aren't yet ready for being installed and find their stuff, I'll work on them...

**Comment by doegox** [comment]
So here is the updated current plan for make install:

```
PREFIX ?= /usr/local

# Brew (OSX, possibly Linux)
Installation PREFIX = $(brew --cellar)/proxmark3/HEAD-$(git describe --always)
Runtime PREFIX = $(brew --prefix)

$PREFIX/bin/proxmark3
$PREFIX/bin/proxmark3-flasher (currently flasher)
$PREFIX/bin/proxmark3-mfkey32 (currently mfkey32)
$PREFIX/bin/proxmark3-mfkey32v2 (currently mfkey32v2)
$PREFIX/bin/proxmark3-mfkey64 (currently mfkey64)
$PREFIX/bin/proxmark3-nonce2key  (currently nonce2key)
# fpga_compress doesn't need to be installed, it's useless outside compilation
#scripts:
$PREFIX/bin/pm3 (currently proxmark3.sh)
$PREFIX/bin/pm3-flash-all (currently flash-all.sh)
$PREFIX/bin/pm3-flash-bootrom (currently flash-bootrom.sh)
$PREFIX/bin/pm3-flash-fullimage (currently flash-fullimage.sh)
$PREFIX/bin/pm3-eml2lower (currently pm3_eml2lower.sh)
$PREFIX/bin/pm3-eml2upper (currently pm3_eml2upper.sh)
$PREFIX/bin/pm3-mfdread (currently pm3_mfdread.py)
$PREFIX/bin/pm3-mfd2eml.py (currently pm3_mfd2eml.py)
$PREFIX/bin/pm3-eml2mfd.py (currently pm3_eml2mfd.py)

$PREFIX/share/proxmark3/lualibs **search DONE**
$PREFIX/share/proxmark3/luascripts **search DONE**

$PREFIX/share/proxmark3/resources/capk.txt **search DONE**
$PREFIX/share/proxmark3/resources/aidlist.json **search DONE**
$PREFIX/share/proxmark3/resources/oids.json **search DONE**
$PREFIX/share/proxmark3/resources/fido2_defparams.json (currently fido2.json)
$PREFIX/share/proxmark3/resources/emv_defparams.json **search DONE**
$PREFIX/share/proxmark3/resources/iclass_dump.bin **search DONE**
$PREFIX/share/proxmark3/resources/hardnested_bf_bench_data.bin **search DONE**
$PREFIX/share/proxmark3/resources/hardnested_tables/* **search DONE**

# these are nice for newcomers to learn I think
$PREFIX/share/proxmark3/traces/*  **search DONE**
$PREFIX/share/doc/proxmark3/* (doc/)

$PREFIX/share/proxmark3/dictionaries/* **search DONE**

$PREFIX/share/proxmark3/firmware/bootrom.elf
$PREFIX/share/proxmark3/firmware/fullimage.elf
$PREFIX/share/proxmark3/firmware/SIM011
$PREFIX/share/proxmark3/firmware/SIM011.sha512.txt

# Linux only:
UDEV_PREFIX:=/etc/udev/rules.d
$UDEV_PREFIX/77-pm3-usb-device-blacklist.rules
```

This requires of course adaptations of the code to find its data.
It also goes with modifications for the user files:
```
~/.proxmark3/history.txt  **DONE**
~/.proxmark3/log_%Y%m%d.txt  **DONE**
~/.proxmark3/dictionaries/ (user dics) **search DONE**
~/.proxmark3/luascripts/ (user lua scripts) **search DONE**
~/.proxmark3/lualibs/ (user lua libs) **search DONE**
~/.proxmark3/cmdscripts/ (user cli scripts)
~/.proxmark3/resources/iclass_key.bin **search DONE**
~/.proxmark3/resources/iclass_decryptionkey.bin **search DONE**
~/.proxmark3/resources/fido2.json (user fido prefs read/write...)
```

[ ] Still need to adapt the scripts `proxmark3.sh` and `flash-*.sh` for being able to work installed

Please comment and tell me if sth is wrong or missing.

**Comment by iceman1001** [comment]
I think you can keep original name for these ones.  There are not proxmark3 bound in that way. 
```
$PREFIX/bin/proxmark3-mfkey32 (currently mfkey32)
$PREFIX/bin/proxmark3-mfkey32v2 (currently mfkey32v2)
$PREFIX/bin/proxmark3-mfkey64 (currently mfkey64)
$PREFIX/bin/proxmark3-nonce2key  (currently nonce2key)
```

And what about the other python scripts in /tools ?

**Comment by doegox** [comment]
yes but they would come with proxmark3 package on some OSes, what if original author wants to package it separately ? we're squatting his namespace

**Comment by doegox** [comment]
So here is the updated current plan for make install:

```
PREFIX ?= /usr/local

# Brew (OSX, possibly Linux)
Installation PREFIX = $(brew --cellar)/proxmark3/HEAD-$(git describe --always)
Runtime PREFIX = $(brew --prefix)

make install:
$PREFIX/bin/pm3 (currently proxmark3.sh)
$PREFIX/bin/pm3-flash-all (currently flash-all.sh)
$PREFIX/bin/pm3-flash-bootrom (currently flash-bootrom.sh)
$PREFIX/bin/pm3-flash-fullimage (currently flash-fullimage.sh)
$PREFIX/share/proxmark3/tools/pm3_eml2lower.sh
$PREFIX/share/proxmark3/tools/pm3_eml2upper.sh
$PREFIX/share/proxmark3/tools/pm3_mfdread.py
$PREFIX/share/proxmark3/tools/pm3_mfd2eml.py
$PREFIX/share/proxmark3/tools/pm3_eml2mfd.py
$PREFIX/share/proxmark3/tools/findbits.py
$PREFIX/share/proxmark3/tools/rfidtest.pl
$PREFIX/share/proxmark3/tools/xorcheck.py
$PREFIX/share/proxmark3/tools/jtag_openocd/ (or $PREFIX/share/proxmark3/jtag_openocd/ ?)
$PREFIX/share/proxmark3/traces/*  **search DONE**
$PREFIX/share/doc/proxmark3/* (doc/)
$PREFIX/share/proxmark3/firmware/SIM011
$PREFIX/share/proxmark3/firmware/SIM011.sha512.txt
# Linux only:
UDEV_PREFIX:=/etc/udev/rules.d
$UDEV_PREFIX/77-pm3-usb-device-blacklist.rules

# make install includes also all the following ones:

make client/install:
$PREFIX/bin/proxmark3
$PREFIX/bin/proxmark3-flasher (currently flasher)
$PREFIX/share/proxmark3/lualibs **search DONE**
$PREFIX/share/proxmark3/luascripts **search DONE**
$PREFIX/share/proxmark3/resources/capk.txt **search DONE**
$PREFIX/share/proxmark3/resources/aidlist.json **search DONE**
$PREFIX/share/proxmark3/resources/oids.json **search DONE**
$PREFIX/share/proxmark3/resources/fido2_defparams.json (currently fido2.json)
$PREFIX/share/proxmark3/resources/emv_defparams.json **search DONE**
$PREFIX/share/proxmark3/resources/iclass_dump.bin **search DONE**
$PREFIX/share/proxmark3/resources/hardnested_bf_bench_data.bin **search DONE**
$PREFIX/share/proxmark3/resources/hardnested_tables/* **search DONE**
$PREFIX/share/proxmark3/dictionaries/* **search DONE**

make mfkey/install:
$PREFIX/share/proxmark3/tools/mfkey32
$PREFIX/share/proxmark3/tools/mfkey32v2
$PREFIX/share/proxmark3/tools/mfkey64

make nonce2key/install:
$PREFIX/share/proxmark3/tools/nonce2key

make bootrom/install:
$PREFIX/share/proxmark3/firmware/bootrom.elf

make fullimage/install:
$PREFIX/share/proxmark3/firmware/fullimage.elf

make recovery/install:
$PREFIX/share/proxmark3/firmware/proxmark3_recovery.bin
```

This requires of course adaptations of the code to find its data.
It also goes with modifications for the user files:
```
~/.proxmark3/history.txt  **DONE**
~/.proxmark3/log_%Y%m%d.txt  **DONE**
~/.proxmark3/dictionaries/ (user dics) **search DONE**
~/.proxmark3/luascripts/ (user lua scripts) **search DONE**
~/.proxmark3/lualibs/ (user lua libs) **search DONE**
~/.proxmark3/cmdscripts/ (user cli scripts)
~/.proxmark3/resources/iclass_key.bin **search DONE**
~/.proxmark3/resources/iclass_decryptionkey.bin **search DONE**
~/.proxmark3/resources/fido2.json (user fido prefs read/write...)
```

[ ] Still need to adapt the scripts `proxmark3.sh` and `flash-*.sh` for being able to work installed

Please comment and tell me if sth is wrong or missing.

**Comment by iceman1001** [comment]
I like this
``` $PREFIX/share/proxmark3/jtag_openocd/ ```


Othervise I would say it is looking like a solid plan.  Not like for one week ago :)

**Comment by doegox** [comment]
ack

**Comment by ZeroChaos-** [comment]
I agree with @doegox that being able to easily build for both proxmark firmware targets at once would be nice.  However, it does quickly reach an obvious limit since there are a bunch of "standalone" options when building the firmware and it makes less sense to ship 12 firmwares.

Not that I'm against that either really, since the firmware is like 300k

**Comment by doegox** [comment]
We've some discussions for having more than one standalone mode in the FW, and some client command to store which one to activate, this would solve this aspect

**Comment by doegox** [comment]
`make install` is live \o/
See https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/md/Development/Maintainers.md for - I hope - useful tips.

**Comment by iceman1001** [comment]
@doegox  Impressive!   Talk about next level.

**Comment by PalinuroSec** [comment]
hello, i am the guy from parrot.
to package this software and reuse the existing makefile, i need to know if all the installation paths have the $DESTDIR prefix

**Comment by doegox** [comment]
Yes, else it's a bug :)

**Comment by PalinuroSec** [comment]
debian packaging almost ready, i'll open a pull request soon, and upload the package on our build platform asap

**Comment by PalinuroSec** [comment]
first experimental pull request (may need some fixes later)
https://github.com/RfidResearchGroup/proxmark3/pull/382

link to our build platform
https://build.parrotsec.org/package/show/parrot-packages/proxmark

if the package works properly, i would like to create a dedicated project on our build platform to build binary artifacts for other distributions like ubuntu, debian, kali or any other debian based plaform you need. we can also build for other systems (suse, fedora, arch etch) but i have never packaged for such distros.

**Comment by iceman1001** [comment]
Is all package maintainers happy with the outcome of **make install** ?
@ZeroChaos-  , @edward-p,  @PalinuroSec

**Comment by edward-p** [comment]
So far so good!

**Comment by ZeroChaos-** [comment]
is there a way to break up "make install" into a few sub tasks?  right now in Pentoo a user can build everything, just the client/proxmark3 target, or the "client/proxmark3 mfkey nonce2key" targets.

Can I get some slightly broken up install targets? :-)

**Comment by doegox** [comment]
`make install` is actually triggering the following individual targets: 

* `make client/install`
* `make bootrom/install`
* `make fullimage/install` (alias of `make armsrc/install`)
* `make recovery/install`
* `make mfkey/install`
* `make nonce2key/install`
* `make fpga_compress/install` (dummy)
* some shared content installation handled by the root Makefile, which can't be installed alone:
  * `pm3-*` scripts
  * `tools/jtag_openocd`, `traces`
  * `doc/md`, `doc/*.md`
  * Tools scripts (`pm3_eml2lower.sh` etc)
  * SIM firmware (beware currently it's binary blob, may break your distro policies on open source)
  * udev rule on Linux

Same logic for `make all`, `make clean`, `make uninstall`

**Comment by doegox** [comment]
@ZeroChaos- If you need a different breakdown, tell me and we'll see what can be adapted

**Comment by ZeroChaos-** [comment]
a separate make client/proxmark3_install and client/proxmark3-flasher would be nice.  I can easily live with out it, but it makes sense that if I'm not building firmware I also don't need to install proxmark3-flasher

the shared stuff you mentioned would be great to break out into like a "make common_install" or something like that.

What is the license on the SIM firmware?  I need a license that allows me to redistribute at a minimum.

**Comment by doegox** [comment]
proxmark3-flasher functionality will soon be merged into proxmark3 client as they share already most of the internals, so we won't spend into packaging details of proxmark3-flasher for now, please understand.

make common/install: I'll look into it.

SIM fw license: @iceman1001 can you check with its author?

**Comment by doegox** [comment]
> make common/install: I'll look into it.

Well that was easy :) Done https://github.com/RfidResearchGroup/proxmark3/commit/7151f3fd50b4c1aa5b37de242e9f5a52364bbce6

**Comment by mwalker33** [comment]
@doegox
"...proxmark3-flasher functionality will soon be merged into proxmark3 client..."
Will there be a way the bootloader image can be checked prior to writing to the boot section on the pm3 ? This may have already been covered.  Given the number of people I have seen write the full image to the boot section, it not included could be a good idea.

just thought.  Thanks.

**Comment by ZeroChaos-** [comment]
INSTALLRELDOCSPATH should be ?= in Makefile.defs

I build with PREFIX=/usr
I install with PREFIX=/usr UDEV_PREFIX=/lib/udev/rules.d INSTALLDOCSRELPATH="share/doc/proxmark3-${version}"

The docs path and udev path are just gentoo policy stuff, the prefix it to install in /usr instead of /usr/local.  The defaults also appear correct, as from source it should default to installing to /usr/local and leave /usr for package manager stuff.  This all looks good to me.  Once you fix the INSTALLDOCSRELPATH to be overridable from env (?= instead of =) I'm good unless you see some override I'm missing which I need.  Please close this issue :-)

Great work all, really appreciate it!

**Comment by iceman1001** [comment]
The binary blob aka compiled sim fw is no problem.   Never were a problem.  Don't know why you thought it was a problem.

**Comment by doegox** [comment]
> Will there be a way the bootloader image can be checked prior to writing to the boot section on the pm3 ? This may have already been covered. Given the number of people I have seen write the full image to the boot section, it not included could be a good idea.

What you described is impossible. Option `-b` doesn't tell the next file is to be interpreted as bootloader, it merely authorized the flasher to write in the bootloader area. The images contain their own addresses.

E.g. `client/proxmark3-flasher /dev/ttyACM0 -b armsrc/obj/fullimage.elf bootrom/obj/bootrom.elf` works equally well. If people bricked their pm3, it must be by other means, e.g. ModemManager interfering.

**Comment by mwalker33** [comment]
Thanks for the info.

**Comment by doegox** [comment]
@ZeroChaos-  RELPATHs are now overridable from the env, but be careful with respecting the same scheme as the default path. E.g.

> INSTALLDOCSRELPATH="share/doc/proxmark3-${version}"

should be written 

INSTALLDOCSRELPATH="/share/doc/proxmark3-${version}/"

**Comment by doegox** [comment]
> What is the license on the SIM firmware? I need a license that allows me to redistribute at a minimum.

The author gave us the source code so now it's in the repo :)
Under GPLv3+
Note that full author name/email details might be adjusted later.
I'm closing this one now that all discussed issues have been fixed, feel free to open new tickets if needed.

**Comment by iceman1001** [comment]
Great work everyone!
Great effort!
And I do hope that all *nix / Proxmark3 users will benefit from this.

**Comment by ZeroChaos-** [comment]
> @ZeroChaos- RELPATHs are now overridable from the env, but be careful with respecting the same scheme as the default path. E.g.
> 
> > INSTALLDOCSRELPATH="share/doc/proxmark3-${version}"
> 
> should be written
> 
> INSTALLDOCSRELPATH="/share/doc/proxmark3-${version}/"

We can argue this one forever, but "REL" means relative paths to me, and those are paths from your relative location.  As such, I made sure it was safe to use a path not starting in / for my invocation :-)

if REL means relative, you should adjust it to actually be relative, if it means something else, you could clarify.  Truthfully, it all works fine and I literally don't care at all :-)

Great work, and thanks for all the support.

**Comment by doegox** [comment]
And you're right and I was lazy changing it everywhere :)
@ZeroChaos- you can use INSTALLDOCSRELPATH="share/doc/proxmark3-${version}" from now on, it's fixed.
